---
all:
  children:
    exchange_servers:
      hosts:
        exchange_target:
          ansible_host: "{{ lookup('ansible.builtin.env', 'EXCHANGE_HOST') }}"
      vars:
        ansible_connection: psrp
        ansible_user: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_USER') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_PASSWORD') }}"
        ansible_port: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_PORT') | default('5986' if lookup('ansible.builtin.env', 'EXCHANGE_WINRM_SCHEME') == 'https' else '5985', true) }}"
        ansible_psrp_protocol: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_SCHEME') | default('http', true) }}"
        ansible_psrp_auth: "{{ lookup('ansible.builtin.env', 'EXCHANGE_PSRP_AUTH') | default('kerberos', true) }}"
        ansible_psrp_negotiate_hostname_override: "{{ lookup('ansible.builtin.env', 'EXCHANGE_SERVER_FQDN') }}"
        ansible_psrp_negotiate_service: "{{ lookup('ansible.builtin.env', 'EXCHANGE_KERBEROS_SERVICE') | default('HTTP', true) }}"
        ansible_psrp_negotiate_delegate: true
        ansible_psrp_message_encryption: always
        ansible_psrp_cert_validation: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_CERT_VALIDATION') | default('validate', true) }}"
        ansible_psrp_ignore_proxy: "{{ lookup('ansible.builtin.env', 'EXCHANGE_IGNORE_PROXY') | default('true', true) }}"
        ansible_psrp_connection_timeout: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_READ_TIMEOUT') | default('70', true) }}"
        ansible_psrp_operation_timeout: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_OPERATION_TIMEOUT') | default('60', true) }}"
        ansible_psrp_read_timeout: "{{ lookup('ansible.builtin.env', 'EXCHANGE_WINRM_READ_TIMEOUT') | default('70', true) }}"
