[libdefaults]
    default_realm = EXCHLAB.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    forwardable = true
    udp_preference_limit = 1

[realms]
    EXCHLAB.LOCAL = {
        kdc = 192.168.6.77
        admin_server = 192.168.6.77
    }

[domain_realm]
    .exchlab.local = EXCHLAB.LOCAL
    exchlab.local = EXCHLAB.LOCAL
